@API_HostAddress = http://localhost:8080
@API_Token = Bearer CfDJ8PO0DKIV0YVAtc6LrPyQDLxiPD_7-ilTqHhSmx6wqreA-jRH2T4rI7SFGBAC1Lo1Vtl87Gv_usQzB4T8UdOOdyUw37CSP21T2LrH765e6K_jTjkc3yWsgt5SRcRkVXvrKFp6hI8QgizZPg20ugVyAoVVqrJ2z_rMCsOXA_3z1_nOfZPhUht2M8VL-p8yKTilM6jzskiMtotdlge2ZzgibtjlZRNYA6KymbVwwyqUXMOopScOzMulrDS2xT8iRq-itQm-ncPeB-BqsUV28d1RNO51OOmb4h9lal7rjXq_z58gG0JGO2iyfeanQTAFWGTyv1LRvumucWtvczbVdZyMH6fCDv2-QE4k36h_p7_4CGh75Sx7WKhoKgJDwqmaufAG9LbOEmhObcjA6DcJamuzgBbbnTpBwG8DWtrHzPeM3yPcj_ohOaL-kgjnLWL_YbAJ254YXytmoyq1lkqBjP0OphiHTAENvUbuqXtcAc2hNXb0fl5Dkf9L4tNO0WQT42CMttFgF_nWx245XtetUKrxiLVZsHrEwMcs2kiK83gBC2m9T-NEtHchTSeFj5qAqLRO4JhTr1WeC-FQr2mfkJBtsih5VxuWuL3TyFC3LiQ2NHCPRplCAf-9FXo51pUWRSMqbghPQot-LoUEA4xXOOTYkMlVfEJ3foan30tyDBS0KzLWQioc1WPYIHaxxIPFa7ejbwnZEvMZJnJLWWvojIidIaXBzHYTu7UlA7BMoBXHT1yPWSdDiCd8iVMmJLev6PtNPzvVj725Mj8XVIkxwYFSdoDr1y4k4DfzYdWkKGoQ3j2Q
@RestaurantId = 996
###
POST {{API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "Owner"
}

###
DELETE {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "owner"
}


###
PATCH {{API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: {{API_Token}}

{
  "DateOfBirth": "1990-01-01",
  "Nationality": "Deutch"
}


###
GET {{API_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{API_HostAddress}}/api/restaurants?searchTerm=urban&pageNumber=1&pageSize=15&sortBy=Name&sortDirection=Descending
Content-Type: application/json
Authorization: {{API_Token}}

###
POST {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}


{
  "Name": "AdminRestaurant",
  "Description": "Fast food restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "admin@abc.com",
  "City": "London",
  "Street": "Baker Street",
  "PostalCode": "12-345"
}

###
PUT {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}

{
  "id": "1003",
  "Name": "OwnerChanged the name",
  "Description": "Updated description",
  "HasDelivery": false
}


###
GET {{API_HostAddress}}/api/restaurants/{{RestaurantId}}
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/19
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json




###
POST {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}


{
  "Name": "Dish 3",
  "Description": "Dish 1 description",
  "KiloCalories": 1,
  "Price": 10
}

###
GET {{API_HostAddress}}/api/restaurants/1003/dishes/1
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json


###

# curl -X 'GET' 
#  'http://localhost:5298/api/restaurants' 
#  -H 'accept: application/json' 
#  -H 'Authorization: Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb4mBS4kRfV5EbEJqT6Zm5CzVzSf9FEthrPqqcgtmgCSa-3DueggeW00VmaBFus1dU4w_uSWeqoN5H7oYPhDrQb066lt3OuZNwppGi3RJGlP2Km93AJZMDICqLgkDsvyxIWI6QfytCDrE68-IA9aAjWNE7jBr23nrOlaO01LUU3ep3nWH15HyXcA6BvywrUC8chpKvxAstgXK9oum5kMkuA5Z7RNeCv3tpB9HlYIGz_PHrVeyaJfkei4I2ZoTGkwdE4FIZmtIdDOLdPJWnifRYx00ZVnte3N5LqhC5ZuVlis-f-bu2YLgJPoC43REtIBMuB6630mNWSiIR0Vc_o0ERbC4P5Li34HSpWVhwlJcfV8bo3HVDwNncWw5iJjo7ulviv3QDbdRpgIomiyFNOx-1Ck7w01eEuEtttJtkPMSAeMa8Mccdcx8GhgLg2l52_4edZca6FXancpZkgHyeTLhIvqvp-2inWnYw9rSJT6v9NPKC6VIUf9_fx2OpyuGy4RWsTHbPjqe5ISIWUg83QYf8tb6WkXGCc2zVsNuinUKK2ES-V3iVaM9KD7vtTclcgiCqQzXWUTClSKBsyofoKK8MvTT57SKx1Y3jMnAIDkgpBcCfuUoP6WEm5e4bhfQv-sr0jxuR8GAmgeaUU0qbEWmA3o0k8Z2t8V8JLhBG8wS7OY_A'
GET {{API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: {{API_Token}}

###

POST  {{API_HostAddress}}/api/restaurants/{{RestaurantId}}/logo
Content-Type: multipart/form-data;boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{API_Token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="jpef.jpg"
Content-Type: image/jpeg


< /Users/loganathansellappa/Documents/jpef.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
