@API_HostAddress = http://localhost:5298
@API_Token = Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb4Yf9Ldqx6K1F4m_t6ZgrvALcxFWdB4kepxOJjaqg5_ExuU0WgJfMKnmRjhCyG37rUqf5G__EcTBgJZ8izeadSbfsnU6pQhlQ3cvEHWnO9A7T83v7OEJb2rAlbJwJ6MXu-4DLVsQt4dVsHTHtuEzNX2UeHoY16ahEh9U-TMD-60boGPWy4LBI_C46oh2RHw9_shud2cCfcsF18K42HTD3xi0y3sOhLpncMH6HY-0esJuS0r7ai0rBWkgvsnOJDQuW2ea8XRgCtqk2bS9mLaLkpdAdJ9wB7w7w446D4GuPNU99Vt1YCOQDm508Z74KMDSi1hPx6gnjQfI8GX8axtqbnAfBxyUlmHHHkc8HwXmeVRM9x2y0JCbb3hvLZ_Y7bQ_LUV9lJZDOWqh2cYQTvmzdESzsj6lWGscDfemUCPv1mjKkWC4WNVR7ieSPGY1Gy5JNLECQ637smXzFXM1BjjDlogEGNFkQqvn4VLHBuwQ-ttb9gxpTHKwfCkQm-LaPk2y4ExgY6I6RYQPdsAyKUxx_Kg5SrCV00eFkYH4c2cJTcLHMBliJz__bA-hYLK3X8ep1wYafLKQgkP3tBqxLyOVfQhdWB6BGCKWmlc91MWuXbkpbjgoIurofUcmPkY3w68ZyktmIv_aCatBMT_BZ2un1nJevV_QpkCx7E68Eu-jDQk1vWBR_5VoP8DmA29GfRnVPLpCfkm_sz6ZziiPPlrdOanJdpw1jjxRjw8Sp_YYgkelEMB9vrqydne3xRaMbqel_HmJQyR90FgWh0sitSRH2NP
@RestaurantId = 996
###
POST {{API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "Owner"
}

###
DELETE {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "owner"
}


###
PATCH {{API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: {{API_Token}}

{
  "DateOfBirth": "1990-01-01",
  "Nationality": "Deutch"
}


###
GET {{API_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{API_HostAddress}}/api/restaurants?searchTerm=urban&pageNumber=1&pageSize=15&sortBy=Name&sortDirection=Descending
Content-Type: application/json
Authorization: {{API_Token}}

###
POST {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}


{
  "Name": "AdminRestaurant",
  "Description": "Fast food restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "admin@abc.com",
  "City": "London",
  "Street": "Baker Street",
  "PostalCode": "12-345"
}

###
PUT {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}

{
  "id": "1003",
  "Name": "OwnerChanged the name",
  "Description": "Updated description",
  "HasDelivery": false
}


###
GET {{API_HostAddress}}/api/restaurants/{{RestaurantId}}
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/19
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json




###
POST {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}


{
  "Name": "Dish 3",
  "Description": "Dish 1 description",
  "KiloCalories": 1,
  "Price": 10
}

###
GET {{API_HostAddress}}/api/restaurants/1003/dishes/1
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json


###

# curl -X 'GET' 
#  'http://localhost:5298/api/restaurants' 
#  -H 'accept: application/json' 
#  -H 'Authorization: Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb4mBS4kRfV5EbEJqT6Zm5CzVzSf9FEthrPqqcgtmgCSa-3DueggeW00VmaBFus1dU4w_uSWeqoN5H7oYPhDrQb066lt3OuZNwppGi3RJGlP2Km93AJZMDICqLgkDsvyxIWI6QfytCDrE68-IA9aAjWNE7jBr23nrOlaO01LUU3ep3nWH15HyXcA6BvywrUC8chpKvxAstgXK9oum5kMkuA5Z7RNeCv3tpB9HlYIGz_PHrVeyaJfkei4I2ZoTGkwdE4FIZmtIdDOLdPJWnifRYx00ZVnte3N5LqhC5ZuVlis-f-bu2YLgJPoC43REtIBMuB6630mNWSiIR0Vc_o0ERbC4P5Li34HSpWVhwlJcfV8bo3HVDwNncWw5iJjo7ulviv3QDbdRpgIomiyFNOx-1Ck7w01eEuEtttJtkPMSAeMa8Mccdcx8GhgLg2l52_4edZca6FXancpZkgHyeTLhIvqvp-2inWnYw9rSJT6v9NPKC6VIUf9_fx2OpyuGy4RWsTHbPjqe5ISIWUg83QYf8tb6WkXGCc2zVsNuinUKK2ES-V3iVaM9KD7vtTclcgiCqQzXWUTClSKBsyofoKK8MvTT57SKx1Y3jMnAIDkgpBcCfuUoP6WEm5e4bhfQv-sr0jxuR8GAmgeaUU0qbEWmA3o0k8Z2t8V8JLhBG8wS7OY_A'
GET {{API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: {{API_Token}}

###

POST  {{API_HostAddress}}/api/restaurants/{{RestaurantId}}/logo
Content-Type: multipart/form-data;boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{API_Token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="jpef.jpg"
Content-Type: image/jpeg


< /Users/loganathansellappa/Documents/jpef.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
