@API_HostAddress = http://localhost:8080
@API_Token = Bearer CfDJ8GElexrW1blKvFWYRAH9-wHUXyzZmhjDXkJykoQYynZQ2V5Z4rz7MIfN16P-qIrnD2yYEMI3Uuye-myT0Tw9T34nGDnJJmeYGtaqjEko83hwwhnGjlEGxn5EX6clOlmhdK-xWGrIvaHXm2sWeECyjLk43qUyIav9zPKysSjoB7Mgokr87iTWuKCpanRknTsJGLSjH8PfjRyBMZpdGdMZJQi0W4CWBq6z54kVxPTuAM05ik6-ztn1BnTa_GBswWpz4dm3rNlF-hOuuHtPV_sf3Jh307Oln4eLFFq-KBJty6VIr1-aKDtmP2jgNqQTGFo0n5neNFrgkb9y8aPcHY8RT37WLeSFodTWdynV3mXlJnlK8tZrOIhqffg-9C24pXrWjdW8CGAZNl8byMMy9yStsDyk54py-53eGewz-NYrfBT14oHeRTXfIQtvgUNW75zya5SBRgIVVk2YgfzRoQLYj094j1FmsyNCxDV1W6jaerP8gcjHeI6qbZOiDgHkDyfWGwXTyD5WMMK2SQpH54p7yBhz2jUDP4eT9HLb2msasSCe5OMThqRZMx8t0P8HE5V7XhhhPVjPSLaf0ZDqqUoAcP8GgKURpiYDAJsylceyDl7CdMk2gywqmAklbeE-ngwuoNK-pVuFRtLMfAlNBt_dN9vGFMQpRrpWHHicZi8QB0zmUqZBFoa5EqhmmrnSrHA_MJiqiUX_Od9hzrZzHfl-rjvcMgtMFBUUGzsv8j7pIzbu2Qu-3DMgBGp9p9bZqf4xD1Jv9PCXa0kU6QARml7tfARyNLVBxw56UZCUHZLgdgFV

###
POST {{API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "Owner"
}

###
DELETE {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "owner"
}


###
PATCH {{API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: {{API_Token}}

{
  "DateOfBirth": "1990-01-01",
  "Nationality": "Deutch"
}


###
GET {{API_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{API_HostAddress}}/api/restaurants?searchTerm=urban&pageNumber=1&pageSize=15&sortBy=Name&sortDirection=Descending
Content-Type: application/json
Authorization: {{API_Token}}

###
POST {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}


{
  "Name": "AdminRestaurant",
  "Description": "Fast food restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "admin@abc.com",
  "City": "London",
  "Street": "Baker Street",
  "PostalCode": "12-345"
}

###
PUT {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}

{
  "id": "1003",
  "Name": "OwnerChanged the name",
  "Description": "Updated description",
  "HasDelivery": false
}


###
GET {{API_HostAddress}}/api/restaurants/1003
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/19
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json




###
POST {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}


{
  "Name": "Dish 3",
  "Description": "Dish 1 description",
  "KiloCalories": 1,
  "Price": 10
}

###
GET {{API_HostAddress}}/api/restaurants/1003/dishes/1
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json


###

# curl -X 'GET' 
#  'http://localhost:5298/api/restaurants' 
#  -H 'accept: application/json' 
#  -H 'Authorization: Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb4mBS4kRfV5EbEJqT6Zm5CzVzSf9FEthrPqqcgtmgCSa-3DueggeW00VmaBFus1dU4w_uSWeqoN5H7oYPhDrQb066lt3OuZNwppGi3RJGlP2Km93AJZMDICqLgkDsvyxIWI6QfytCDrE68-IA9aAjWNE7jBr23nrOlaO01LUU3ep3nWH15HyXcA6BvywrUC8chpKvxAstgXK9oum5kMkuA5Z7RNeCv3tpB9HlYIGz_PHrVeyaJfkei4I2ZoTGkwdE4FIZmtIdDOLdPJWnifRYx00ZVnte3N5LqhC5ZuVlis-f-bu2YLgJPoC43REtIBMuB6630mNWSiIR0Vc_o0ERbC4P5Li34HSpWVhwlJcfV8bo3HVDwNncWw5iJjo7ulviv3QDbdRpgIomiyFNOx-1Ck7w01eEuEtttJtkPMSAeMa8Mccdcx8GhgLg2l52_4edZca6FXancpZkgHyeTLhIvqvp-2inWnYw9rSJT6v9NPKC6VIUf9_fx2OpyuGy4RWsTHbPjqe5ISIWUg83QYf8tb6WkXGCc2zVsNuinUKK2ES-V3iVaM9KD7vtTclcgiCqQzXWUTClSKBsyofoKK8MvTT57SKx1Y3jMnAIDkgpBcCfuUoP6WEm5e4bhfQv-sr0jxuR8GAmgeaUU0qbEWmA3o0k8Z2t8V8JLhBG8wS7OY_A'
GET {{API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: {{API_Token}}

###

