@API_HostAddress = http://localhost:5298

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "MediatorR",
  "Description": "Fast food restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "sda@abc.com",
  "City": "London",
  "Street": "Baker Street",
  "PostalCode": "12-345"
}

###
PUT {{API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "id": "1003",
  "Name": "ChangedName",
  "Description": "Updated description",
  "HasDelivery": false
}

###
GET {{API_HostAddress}}/api/restaurants

<> 2024-10-03T140155.200.json

###
GET {{API_HostAddress}}/api/restaurants/1003

<> 2024-10-03T225827.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/19

<> 2024-10-03T225827.200.json




###
POST {{API_HostAddress}}/api/restaurants/1003/dishes
Content-Type: application/json

{
  "Name": "Dish 2",
  "Description": "Dish 1 description",
  "KiloCalories": 1,
  "Price": 10
}

###
GET {{API_HostAddress}}/api/restaurants/1003/dishes/1

<> 2024-10-03T140155.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/00/dishes

<> 2024-10-03T140155.200.json
