@API_HostAddress = http://localhost:5298
@API_Token = Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb7KgyLNOmY58BLtGjJ3v29H0mAuHJadqY0AtopcSF8unyuxj0KNlIPEsHwHlrRUKYwNVQZ_yqKANGyoNa3EKgQ4o-rztCEQW1MiXRIeYspsIJax_iYwi_ifc0ZoW-D5rnZKhD3k5kv3S5lq7ybiduptBAH9n9LOxUqUBDq9DtDfov9qz4OE7VUEs5hXl5ONtUqeoarzBNa3ismbftBrnq8i7NSN64CumN1nh4719L8zjFleaNPzjpARDzC6saBfZ9Qhgh6mp8EKbudrVt8r-ZUlVNJOKqm0CnEQ7TeBZWSzqe6tFVdDM53T9YlAwtU_8PltkCw3t8dWM9gxumKGDR-ZpKmsqZyBwlX9hEDQwWXZ57Fzt28iKgyckBTurXWq-lgWA9w7ZuE4KcvxIdtrM1hkzFRACwez-CZIfneLI8P2b9pUnBrmY2-XiufrzG9FhHrpttUMgKrJQI6HZhAXc8onxwNxLCZb1AsYSDLIJLIeMLYEn3b43DsdAZHHbMV-suNyfhhYAbUnTLzxelsh4Jy2tOMseJyagtCgRHg8Lu-TjpbTR5yqSan4wl9Z0gWMU8xRwwpAVLRUeqb0D3BFRVxj_m1b9MM9vtCrHvxk7onVo-Qu183tm7eM8PxJUi8HfLV4FEqC7dpC5rYfGgYlksAbzzKCBdcNK8vHlnR1hci6vNQtwWH-N8XwkZGNuowZI8k-qGJ1t2u80MnVd_NGmBeXVEZWYzp6olBPbJblU1FJ0ryHLXmcYGigjnoin0C-Tszf8p0Oj1BWXxk99BBQbByZ5soptACb_tfNzC84Rge0-9kb9nO8YMSn_DYcW1z-1FA0KowVGPuDJabxc8iJxYd8y7GS0Fs47Kk5etlYrNZ2WSzawV9WC1PeEomBMxrVrMc

###
POST {{API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "admin@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "Owner"
}

###
DELETE {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "owner"
}


###
PATCH {{API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: {{API_Token}}

{
  "DateOfBirth": "1990-01-01",
  "Nationality": "Deutch"
}


###
GET {{API_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}

###
POST {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}


{
  "Name": "MediatorR",
  "Description": "Fast food restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "sda@abc.com",
  "City": "London",
  "Street": "Baker Street",
  "PostalCode": "12-345"
}

###
PUT {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}

{
  "id": "1003",
  "Name": "ChangedName",
  "Description": "Updated description",
  "HasDelivery": false
}


###
GET {{API_HostAddress}}/api/restaurants/1003
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/19
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json




###
POST {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}


{
  "Name": "Dish 3",
  "Description": "Dish 1 description",
  "KiloCalories": 1,
  "Price": 10
}

###
GET {{API_HostAddress}}/api/restaurants/1003/dishes/1
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json


###

# curl -X 'GET' 
#  'http://localhost:5298/api/restaurants' 
#  -H 'accept: application/json' 
#  -H 'Authorization: Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb4mBS4kRfV5EbEJqT6Zm5CzVzSf9FEthrPqqcgtmgCSa-3DueggeW00VmaBFus1dU4w_uSWeqoN5H7oYPhDrQb066lt3OuZNwppGi3RJGlP2Km93AJZMDICqLgkDsvyxIWI6QfytCDrE68-IA9aAjWNE7jBr23nrOlaO01LUU3ep3nWH15HyXcA6BvywrUC8chpKvxAstgXK9oum5kMkuA5Z7RNeCv3tpB9HlYIGz_PHrVeyaJfkei4I2ZoTGkwdE4FIZmtIdDOLdPJWnifRYx00ZVnte3N5LqhC5ZuVlis-f-bu2YLgJPoC43REtIBMuB6630mNWSiIR0Vc_o0ERbC4P5Li34HSpWVhwlJcfV8bo3HVDwNncWw5iJjo7ulviv3QDbdRpgIomiyFNOx-1Ck7w01eEuEtttJtkPMSAeMa8Mccdcx8GhgLg2l52_4edZca6FXancpZkgHyeTLhIvqvp-2inWnYw9rSJT6v9NPKC6VIUf9_fx2OpyuGy4RWsTHbPjqe5ISIWUg83QYf8tb6WkXGCc2zVsNuinUKK2ES-V3iVaM9KD7vtTclcgiCqQzXWUTClSKBsyofoKK8MvTT57SKx1Y3jMnAIDkgpBcCfuUoP6WEm5e4bhfQv-sr0jxuR8GAmgeaUU0qbEWmA3o0k8Z2t8V8JLhBG8wS7OY_A'
GET {{API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: {{API_Token}}

###

