@API_HostAddress = http://localhost:5298
@API_Token = Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb7VWA1b-3ZWSINSG9yF4wxiMc33qMUZaa9zp3KWHzQU2gqJ89OBkahfKRuwnztRyUry52HWBTFF3LDVL2LmZ8_mg6VrImjiBQbuixKjkpQtPuD7GsYMH0GE0iele4nbbYjcdhvm0-eD2JJMqjU_Y2SXGgXlRLc8QYuN2AwXt-bFX6tKz0ctfLx2wYCjBA3oJByyGYPWRaQggBiN4JAPQxA9wK9gI377CARzkWZ-re6mf9f6UCcqtyem5Ciy3dyYDmWzwSaowUuNPZ6a08xAX-RaexhXXNnlS_sGm1JPs1PPETyW3M9B5YkAXAKFVhm08sD-E3hgKHzaQlI83dQFkJXHohvoe0aWyaGY63hylaxL-BGebH1TA-UomSi_2vS6RS9d0ODf0oddLGUdevFwK_kJWvE-lN7FojI4F4izZYyvGmUnMCDClWTseMbVDZN4FdKBsslyx01u4s_ie7z_w1nA_2OT_v2OcVTyesSWqtb7gqWaZ0SOI8rASSfbphdW9utMBcmNbQfWM3gqhmOSXJDztvxeoQIZBGpGURILYQfGNvpzqMSnH7oj6G8U_6SnKEkUS9Y5rPaFpxgGV2WTJbj4TENJP4Qo_RN4uQmlbz5ddUudBbEPYPVNPQh-lMKLdN-n1jXGQDiPSJj05U6adWw_sVmQAxETybp4HScDJibfQTeCJhvFMx-R-nURFkb34BEkuI5YGplKN4tVuy0tbsZ-c9VfoCqlWaCU6Rc0CnA9URK6jqjgd56c4maqgfuktohckT-3LuPI51PLiDf3_rETFoAsXU0_50kWmHSZUNQzSw

###
POST {{API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@testdevlogan.com",
  "password": "abcTest123!"
}

###
POST {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "Owner"
}

###
DELETE {{API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: {{API_Token}}

{
  "UserEmail": "owner@testdevlogan.com",
  "RoleName": "owner"
}


###
PATCH {{API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: {{API_Token}}

{
  "DateOfBirth": "1990-01-01",
  "Nationality": "DE"
}


###
GET {{API_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{API_HostAddress}}/api/restaurants
Content-Type: application/json

###
POST {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}


{
  "Name": "MediatorR",
  "Description": "Fast food restaurant",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "sda@abc.com",
  "City": "London",
  "Street": "Baker Street",
  "PostalCode": "12-345"
}

###
PUT {{API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: {{API_Token}}

{
  "id": "1003",
  "Name": "ChangedName",
  "Description": "Updated description",
  "HasDelivery": false
}


###
GET {{API_HostAddress}}/api/restaurants/1003
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/19
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T225827.200.json




###
POST {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}


{
  "Name": "Dish 3",
  "Description": "Dish 1 description",
  "KiloCalories": 1,
  "Price": 10
}

###
GET {{API_HostAddress}}/api/restaurants/1003/dishes/1
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json

###
DELETE {{API_HostAddress}}/api/restaurants/1003/dishes
Accept: application/json
Authorization: {{API_Token}}

<> 2024-10-03T140155.200.json


###

# curl -X 'GET' 
#  'http://localhost:5298/api/restaurants' 
#  -H 'accept: application/json' 
#  -H 'Authorization: Bearer CfDJ8HxAzmAEXAdMjR2nAB2Xwb4mBS4kRfV5EbEJqT6Zm5CzVzSf9FEthrPqqcgtmgCSa-3DueggeW00VmaBFus1dU4w_uSWeqoN5H7oYPhDrQb066lt3OuZNwppGi3RJGlP2Km93AJZMDICqLgkDsvyxIWI6QfytCDrE68-IA9aAjWNE7jBr23nrOlaO01LUU3ep3nWH15HyXcA6BvywrUC8chpKvxAstgXK9oum5kMkuA5Z7RNeCv3tpB9HlYIGz_PHrVeyaJfkei4I2ZoTGkwdE4FIZmtIdDOLdPJWnifRYx00ZVnte3N5LqhC5ZuVlis-f-bu2YLgJPoC43REtIBMuB6630mNWSiIR0Vc_o0ERbC4P5Li34HSpWVhwlJcfV8bo3HVDwNncWw5iJjo7ulviv3QDbdRpgIomiyFNOx-1Ck7w01eEuEtttJtkPMSAeMa8Mccdcx8GhgLg2l52_4edZca6FXancpZkgHyeTLhIvqvp-2inWnYw9rSJT6v9NPKC6VIUf9_fx2OpyuGy4RWsTHbPjqe5ISIWUg83QYf8tb6WkXGCc2zVsNuinUKK2ES-V3iVaM9KD7vtTclcgiCqQzXWUTClSKBsyofoKK8MvTT57SKx1Y3jMnAIDkgpBcCfuUoP6WEm5e4bhfQv-sr0jxuR8GAmgeaUU0qbEWmA3o0k8Z2t8V8JLhBG8wS7OY_A'
GET {{API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: {{API_Token}}

###

